version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
workflows:
  build_and_push_site:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
                - feature/deploy-to-branch
          cluster-name: CIRCLE_BRANCH+'_pay_ecs_Payments'
          family: CIRCLE_BRANCH+'Stack"+CIRCLE_BRANCH+"payecspaySitepaymentSiteServiceTaskDef8814A6F9'
          service-name: CIRCLE_BRANCH+'Stack-"+CIRCLE_BRANCH+"payecspaySitepaymentSiteService735C5EA0-b9ZeluJTims3'
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
  build_and_push_calculator:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
          cluster-name: 'dev_pay_ecs_Payments'
          family: 'devStackdevpayecscalculatorcalculatorTask1ED54CB3'
          service-name: 'devStack-devpayecscalculatorcalculatorService340918A9-h8ejb8OfoZ7R'
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
