version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
workflows:
  build_and_push_site:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: $CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
          cluster-name: "dev_pay_ecs_Payments"
          family: "devStackdevpayecspaySitepaymentSiteServiceTaskDef8814A6F9"
          service-name: "devStack-devpayecspaySitepaymentSiteService735C5EA0-0N0hrHOvoPFa"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - stage
          cluster-name: "stage_pay_ecs_Payments"
          family: "stageStackstagepayecspaySitepaymentSiteServiceTaskDef06EA38A0"
          service-name: "stageStack-stagepayecspaySitepaymentSiteServiceA490E237-7gnuYguViwew"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - prod
          cluster-name: "prod_pay_ecs_PaymentsUpdate "
          family: "prodStackprodpayecspaySitepaymentSiteServiceTaskDefCB42646A"
          service-name: "prodStack-prodpayecspaySitepaymentSiteService7D42131B-AbNNE2P4GcW0"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
  build_and_push_calculator:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: $CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
          cluster-name:  "dev_pay_ecs_Payments"
          family: "devStackdevpayecscalculatorcalculatorTask1ED54CB3"
          service-name: "devpayecscalculatorcalculatorService340918A9-mpkABvsKD0Ip"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - stage
          cluster-name:  "stage_pay_ecs_Payments"
          family: "stageStackstagepayecscalculatorcalculatorTaskE2CCA8D9"
          service-name: "stageStack-stagepayecscalculatorcalculatorService2037D9D6-W8W37yjQ7614"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - prod
          cluster-name:  "prod_pay_ecs_Payments"
          family: "prodStackprodpayecscalculatorcalculatorTask56C667E4"
          service-name: "prodStack-prodpayecscalculatorcalculatorService4074FCCD-WwSPmUBBRmig"
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image