version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "feature/docker-ecr" ]; then  
              docker login --help | grep password
              echo "aws version"
              aws --version
              echo "Access key"
              echo $AWS_ACCESS_KEY_ID
              echo "region"
              echo $AWS_DEFAULT_REGION
              echo "getting password"
              export DOCKER_LOGIN=$(aws ecr get-login)
              echo "trying login"
              $DOCKER_LOGIN
              
              
              docker tag app 548668861663.dkr.ecr.us-east-2.amazonaws.com/subless-pay:dev
              docker push 548668861663.dkr.ecr.us-east-2.amazonaws.com/subless-pay:dev
            fi