version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  build-site:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: 'dev'


  build-calculator:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: 'dev'

workflows:
  build_only_site:
    jobs:
      - build-site
  build_and_push_site:
    when:
      or:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ dev, << pipeline.git.branch >> ]
        - equal: [ stage, << pipeline.git.branch >> ]
        - equal: [ prod, << pipeline.git.branch >> ]
    jobs:
      - build-site
      - aws-ecs/deploy-service-update:
          cluster-name: 'dev_pay_ecs_Payments'
          family: 'devStackdevpayecspaySitepaymentSiteServiceTaskDef8814A6F9'
          service-name: 'devStack-devpayecspaySitepaymentSiteService735C5EA0-b9ZeluJTims3'
          force-new-deployment: true
          requires: 
            - build-site

  build_only_calculator:
    jobs:
      - build-calculator
  build_and_push_calculator:
    when:
      or:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ dev, << pipeline.git.branch >> ]
        - equal: [ stage, << pipeline.git.branch >> ]
        - equal: [ prod, << pipeline.git.branch >> ]
    jobs:
      - build-calculator
      - aws-ecs/deploy-service-update:
          cluster-name: 'dev_pay_ecs_Payments'
          family: 'devStackdevpayecscalculatorcalculatorTask1ED54CB3'
          service-name: 'devStack-devpayecscalculatorcalculatorService340918A9-h8ejb8OfoZ7R'
          force-new-deployment: true
          requires:
            -  build-calculator
