version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  browser-tools: circleci/browser-tools@1.2.1
workflows:
  build_and_push_site:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-push-site-commit-tag
          filters:
            branches:
              ignore:
                - dev
                - stage
                - prod
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: $CIRCLE_SHA1
      - aws-ecr/build-and-push-image:
          name: build-push-site-env-tag
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
          account-url: AWS_ACCOUNT_URL
          extra-build-args: --build-arg build_environment=$CIRCLE_BRANCH
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: '${CIRCLE_BRANCH},${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          name: deploy-site-to-dev
          filters:
            branches:
              only:
                - dev
          cluster-name: $DEV_CLUSTER_NAME
          family: $DEV_SITE_TASK
          service-name: $DEV_SITE_SERVICE
          force-new-deployment: true       
          container-image-name-updates: "container=web,tag=${CIRCLE_SHA1}"   
          requires:
            - build-push-site-env-tag
      - aws-ecs/deploy-service-update:
          name: deploy-site-to-stage
          filters:
            branches:
              only:
                - stage
          cluster-name: $STAGE_CLUSTER_NAME
          family: $STAGE_SITE_TASK
          service-name: $STAGE_SITE_SERVICE
          container-image-name-updates: "container=web,tag=${CIRCLE_SHA1}"
          force-new-deployment: true
          requires:
            - build-push-site-env-tag
      - aws-ecs/deploy-service-update:
          name: deploy-site-to-prod
          filters:
            branches:
              only:
                - prod
          cluster-name: $PROD_CLUSTER_NAME
          family: $PROD_SITE_TASK
          service-name: $PROD_SITE_SERVICE
          container-image-name-updates: "container=web,tag=${CIRCLE_SHA1}"
          force-new-deployment: true
          requires:
            - build-push-site-env-tag
  build_and_push_calculator:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-push-calc-commit-tag
          filters:
            branches:
              ignore:
                - dev
                - stage
                - prod
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: $CIRCLE_SHA1
      - aws-ecr/build-and-push-image:
          name: build-push-calc-env-tag
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: $CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          name: deploy-calc-to-dev
          filters:
            branches:
              only:
                - dev
          cluster-name: $DEV_CLUSTER_NAME
          family: $DEV_CALC_TASK
          service-name: $DEV_CALC_SERVICE
          force-new-deployment: true
          container-image-name-updates: "container=dev_pay2_ecs_calculator_calculatorContainer,tag=dev"
          requires:
            - build-push-calc-env-tag
      - aws-ecs/deploy-service-update:
          name: deploy-calc-to-stage
          filters:
            branches:
              only:
                - stage
          cluster-name: $STAGE_CLUSTER_NAME
          family: $STAGE_CALC_TASK
          service-name: $STAGE_CALC_SERVICE
          force-new-deployment: true
          container-image-name-updates: "container=stage_pay2_ecs_calculator_calculatorContainer,tag=stage"
          requires:
            - build-push-calc-env-tag
      - aws-ecs/deploy-service-update:
          name: deploy-calc-to-prod
          filters:
            branches:
              only:
                - prod
          cluster-name: $PROD_CLUSTER_NAME
          family: $PROD_CALC_TASK
          service-name: $PROD_CALC_SERVICE
          container-image-name-updates: "container=prod_pay2_ecs_calculator_calculatorContainer,tag=prod"
          force-new-deployment: true
          requires:
            - build-push-calc-env-tag
  selenium:
    docker:
      - image: cimg/python:3.9-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/Subless.UI.Tests
    steps:
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv virtual_env --clear
            source virtual_env/bin/activate
            pip install --trusted-host https://pypi.python.org -r requirements.txt
      - run:
          name: Run tests
          command: |
            python3 -m pytest Tests

