version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  setupenv:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: "Setup custom environment variables"
          command: echo 'export $CLUSTERNAME=$CIRCLE_BRANCH"_pay_ecs_Payments"' >> $BASH_ENV
      - run:
          name: "Setup custom environment variables"
          command: echo 'export $SITETASKNAME=$CIRCLE_BRANCH"Stack"$CIRCLE_BRANCH"payecspaySitepaymentSiteServiceTaskDef8814A6F9"' >> $BASH_ENV
      - run:
          name: "Setup custom environment variables"
          command: echo 'export $SITESERVICENAME=$CIRCLE_BRANCH"Stack-"$CIRCLE_BRANCH"payecspaySitepaymentSiteService735C5EA0-b9ZeluJTims3"' >> $BASH_ENV
      - run:
          name: "Setup custom environment variables"
          command: echo 'export $CALCTASKNAME=$CIRCLE_BRANCH"Stack"$CIRCLE_BRANCH"payecscalculatorcalculatorTask1ED54CB3"' >> $BASH_ENV
      - run:
          name: "Setup custom environment variables"
          command: echo 'export $CALCSERVICENAME=$CIRCLE_BRANCH"Stack-"$CIRCLE_BRANCH"payecscalculatorcalculatorService340918A9-mpkABvsKD0Ip"' >> $BASH_ENV
workflows:
  build_and_push_site:
    jobs:
      - setupenv
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-pay
          skip-when-tags-exist: false
          tag: $CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
                - feature/deploy-to-branch
          cluster-name: ${CLUSTERNAME}
          family: ${SITETASKNAME}
          service-name: ${SITESERVICENAME}
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
  build_and_push_calculator:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: CalculatorDockerfile
          path: ./
          region: AWS_DEFAULT_REGION
          repo: subless-calculator
          skip-when-tags-exist: false
          tag: $CIRCLE_BRANCH
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - dev
                - stage
                - prod
          cluster-name:  ${CLUSTERNAME}
          family: ${CALCTASKNAME}
          service-name: ${CALCSERVICENAME}
          force-new-deployment: true
          requires:
            - aws-ecr/build-and-push-image
